### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by pilotpirxie** [theogravity/graphql-giraphql-server-example#1]
Hi @theogravity ! First of all, impressive project. Congratulations! Do you have in plan to write a step-by-step tutorial about components and how to use/develop/extend the server from your example? Regards! :)

**Comment by theogravity** [comment]
Hi, thanks for the comments. Probably not. It's kind of a test bed for things I may try out at work or not and to see what the potential limits are.

People are always welcome to contribute in any way they wish to improve the examples.
